//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checkout.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public System.Guid ID { get; set; }
        public string ItemID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
